# Ex1 - Filtering and Sorting Data

This time we are going to pull data directly from the internet.
Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

### Step 1. Import the necessary libraries

In [2]:
import numpy as np
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv).

### Step 3. Assign it to a variable called chipo.

In [3]:
url = "https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv"

chipo = pd.read_csv(url,sep='\t')

### Step 4. How many products cost more than $10.00?

In [11]:
item_greater = chipo['item_price'].replace('[\$,]', '', regex=True).astype(float) > 10
item_greater.count()

4622

### Step 5. What is the price of each item? 
###### print a data frame with only two columns item_name and item_price

In [15]:
name_price = chipo[['item_name','item_price']]
name_price

                                  item_name item_price
0              Chips and Fresh Tomato Salsa     $2.39
1                                      Izze     $3.39
2                          Nantucket Nectar     $3.39
3     Chips and Tomatillo-Green Chili Salsa     $2.39
4                              Chicken Bowl    $16.98
5                              Chicken Bowl    $10.98
6                             Side of Chips     $1.69
7                             Steak Burrito    $11.75
8                          Steak Soft Tacos     $9.25
9                             Steak Burrito     $9.25
10                      Chips and Guacamole     $4.45
11                     Chicken Crispy Tacos     $8.75
12                       Chicken Soft Tacos     $8.75
13                             Chicken Bowl    $11.25
14                      Chips and Guacamole     $4.45
15    Chips and Tomatillo-Green Chili Salsa     $2.39
16                          Chicken Burrito     $8.49
17                          Chicken Burrito     $8.49
18                              Canned Soda     $2.18
19                             Chicken Bowl     $8.75
20                      Chips and Guacamole     $4.45
21                         Barbacoa Burrito     $8.99
22                         Nantucket Nectar     $3.39
23                          Chicken Burrito    $10.98
24                                     Izze     $3.39
25             Chips and Fresh Tomato Salsa     $2.39
26                             Chicken Bowl     $8.49
27                         Carnitas Burrito     $8.99
28                              Canned Soda     $1.09
29                          Chicken Burrito     $8.49
...                                     ...        ...
4592                       Barbacoa Burrito    $11.75
4593                          Carnitas Bowl    $11.75
4594                          Barbacoa Bowl    $11.75
4595                           Chicken Bowl     $8.75
4596                    Chips and Guacamole     $4.45
4597                      Canned Soft Drink     $1.25
4598                          Bottled Water     $1.50
4599                           Chicken Bowl     $8.75
4600                    Chips and Guacamole     $4.45
4601                      Canned Soft Drink     $1.25
4602                       Barbacoa Burrito     $9.25
4603                       Barbacoa Burrito     $9.25
4604                           Chicken Bowl     $8.75
4605                    Chips and Guacamole     $4.45
4606                      Canned Soft Drink     $1.25
4607                          Steak Burrito    $11.75
4608                         Veggie Burrito    $11.25
4609                      Canned Soft Drink     $1.25
4610                          Steak Burrito    $11.75
4611                         Veggie Burrito    $11.25
4612                          Carnitas Bowl     $9.25
4613                                  Chips     $2.15
4614                          Bottled Water     $1.50
4615                     Chicken Soft Tacos     $8.75
4616                    Chips and Guacamole     $4.45
4617                          Steak Burrito    $11.75
4618                          Steak Burrito    $11.75
4619                     Chicken Salad Bowl    $11.25
4620                     Chicken Salad Bowl     $8.75
4621                     Chicken Salad Bowl     $8.75

[4622 rows x 2 columns]

### Step 6. Sort by the name of the item

In [17]:
name_price.sort_values(by='item_name')

              item_name item_price
3389  6 Pack Soft Drink    $12.98
341   6 Pack Soft Drink     $6.49
1849  6 Pack Soft Drink     $6.49
1860  6 Pack Soft Drink     $6.49
2713  6 Pack Soft Drink     $6.49
3422  6 Pack Soft Drink     $6.49
553   6 Pack Soft Drink     $6.49
1916  6 Pack Soft Drink     $6.49
1922  6 Pack Soft Drink     $6.49
1937  6 Pack Soft Drink     $6.49
3836  6 Pack Soft Drink     $6.49
298   6 Pack Soft Drink     $6.49
1976  6 Pack Soft Drink     $6.49
1167  6 Pack Soft Drink     $6.49
3875  6 Pack Soft Drink     $6.49
1124  6 Pack Soft Drink     $6.49
3886  6 Pack Soft Drink     $6.49
2108  6 Pack Soft Drink     $6.49
3010  6 Pack Soft Drink     $6.49
4535  6 Pack Soft Drink     $6.49
4169  6 Pack Soft Drink     $6.49
4174  6 Pack Soft Drink     $6.49
4527  6 Pack Soft Drink     $6.49
4522  6 Pack Soft Drink     $6.49
3806  6 Pack Soft Drink     $6.49
2389  6 Pack Soft Drink     $6.49
3132  6 Pack Soft Drink     $6.49
3141  6 Pack Soft Drink     $6.49
639   6 Pack Soft Drink     $6.49
1026  6 Pack Soft Drink     $6.49
...                 ...        ...
2996       Veggie Salad     $8.49
3163       Veggie Salad     $8.49
4084       Veggie Salad     $8.49
1694       Veggie Salad     $8.49
2756       Veggie Salad     $8.49
4201  Veggie Salad Bowl    $11.25
1884  Veggie Salad Bowl    $11.25
455   Veggie Salad Bowl    $11.25
3223  Veggie Salad Bowl    $11.25
2223  Veggie Salad Bowl     $8.75
2269  Veggie Salad Bowl     $8.75
4541  Veggie Salad Bowl     $8.75
3293  Veggie Salad Bowl     $8.75
186   Veggie Salad Bowl    $11.25
960   Veggie Salad Bowl     $8.75
1316  Veggie Salad Bowl     $8.75
2156  Veggie Salad Bowl    $11.25
4261  Veggie Salad Bowl    $11.25
295   Veggie Salad Bowl    $11.25
4573  Veggie Salad Bowl     $8.75
2683  Veggie Salad Bowl     $8.75
496   Veggie Salad Bowl    $11.25
4109  Veggie Salad Bowl    $11.25
738   Veggie Soft Tacos    $11.25
3889  Veggie Soft Tacos    $16.98
2384  Veggie Soft Tacos     $8.75
781   Veggie Soft Tacos     $8.75
2851  Veggie Soft Tacos     $8.49
1699  Veggie Soft Tacos    $11.25
1395  Veggie Soft Tacos     $8.49

[4622 rows x 2 columns]

### Step 7. What was the quantity of the most expensive item ordered?

In [24]:
chipo.sort_values(by = "item_price", ascending = False).head(1)

,order_id,quantity,item_name,choice_description,item_price
2624,1042,1,Steak Salad Bowl,"[Fresh Tomato Salsa, [Black Beans, Sour Cream,...",$9.39

### Step 8. How many times were a Veggie Salad Bowl ordered?

In [25]:
chipo_salad = chipo[chipo.item_name == "Veggie Salad Bowl"]

len(chipo_salad)

18

### Step 9. How many times people orderd more than one Canned Soda?

In [26]:
chipo_drink_steak_bowl = chipo[(chipo.item_name == "Canned Soda") & (chipo.quantity > 1)]
len(chipo_drink_steak_bowl)

20